name: Build ECTS

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ECTS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Build assets
        run: sudo apt-get install -y nodejs && ls -la && cd web && npm install && npm run build
      - name: Packaging assets
        run: cd ../ && go install github.com/shuLhan/go-bindata/v4/cmd/go-bindata@latest && go-bindata -pkg web -o web/bindata.go web/dist/...
      - name: Build ECTS application
        run: |
          GO111MODULE=on go get
          GO111MODULE=on GOOS=darwin go build -ldflags "-s -w" -o "bin/ects_darwin" main.go
          GO111MODULE=on GOOS=linux go build -ldflags "-s -w" -o "bin/ects_linux" main.go